import "./globals.css";
import "swiper/css";


export const metadata = {
  title: "Silver",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ar">
      <body
      >
        {children}
      </body>
    </html>
  );
}
